AWS_DATA_PATH="${HOME}/.aws"
AWS_CONFIG_FILE="${AWS_DATA_PATH}/config"
AWS_SHARED_CREDENTIALS_FILE="${AWS_DATA_PATH}/credentials"
AWS_DEFAULT_REGION="us-east-2"
AWS_DEFAULT_OUTPUT="json"

export AWS_DATA_PATH AWS_CONFIG_FILE AWS_SHARED_CREDENTIALS_FILE AWS_DEFAULT_REGION AWS_DEFAULT_OUTPUT
