name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Setup pre-commit
        run: |
          command -v pre-commit || pip install pre-commit

      - name: Execute pre-commit
        run: |
          make pre-commit
